# Generated by Django 5.0.2 on 2025-05-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("common_name", models.CharField(max_length=100)),
                ("cca2", models.CharField(max_length=2, unique=True)),
                ("cca3", models.CharField(max_length=3)),
                ("capital", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(max_length=100)),
                ("subregion", models.CharField(blank=True, max_length=100, null=True)),
                ("population", models.BigIntegerField()),
                ("flag_url", models.URLField(max_length=500)),
                ("flag_emoji", models.CharField(blank=True, max_length=10, null=True)),
                ("timezones", models.JSONField(default=list)),
                ("languages", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
    ]
